language: node_js
node_js:
  - node
env:
  - MY_VAR=EverythignIsAwesome
  - NODE_ENV=TEST
  # - secure: TsYgfDTXM9DhteoxruftAIm9qbcVFTfBbPmi/Mv9lGkDKZ/b4pputXgbfy2On7dsu5s9Bio/P4Nri61sgVHZm6AJIsNWf2D6Ggiz94oddr0r+7dPp9yqTziPQAKNmMSzCtLff9Dl4BSOiasy/aQy5M+NrD6kXex0xjZyTIEndzk=
before_install:
  - openssl aes-256-cbc -K $encrypted_cfd49ee2eab2_key -iv $encrypted_cfd49ee2eab2_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 45.76.1.31\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - npm install -g pm2
  - npm test
after_success:
  - npm prune --production  # 删除devDependencies
  - tar -jcvf demo.tar.bz2 *    # 打包并压缩代码
  - scp demo.tar.bz2 root@45.76.1.31:~/  # 复制到生产服务器上
  - ssh root@45.76.1.31 'mkdir -p demo && tar -jfxv demo.tar.bz2 -C demo'
  - ssh root@45.76.1.31 'cd demo && pm2 hello.js'